src/Entity/Item.php
<?php

namespace App\Entity;

use App\Repository\ItemRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\PersistentCollection;

#[ORM\Entity(repositoryClass: ItemRepository::class)]
class Item
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'datetime')]
    private $createDate;

    #[ORM\ManyToOne(targetEntity: Collection::class)]
    #[ORM\JoinColumn(nullable: false)]
    private $collection;

    #[ORM\OneToMany(mappedBy: 'item', targetEntity: ItemAttribute::class, orphanRemoval: true, cascade:['persist'])]
    private $attributes;

    #[ORM\OneToMany(mappedBy: 'item', targetEntity: Like::class)]
    private $likes;

    #[ORM\ManyToMany(targetEntity: Tags::class, inversedBy: 'items')]
    private $tags;

    public function __construct()
    {
        $this->attributes = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCreateDate(): \DateTimeInterface
    {
        return $this->createDate;
    }

    public function setCreateDate(\DateTimeInterface $createDate): self
    {
        $this->createDate = $createDate;

        return $this;
    }

    /**
     * @return PersistentCollection|ItemAttribute[]
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    public function addItemAttribute(ItemAttribute $itemAttribute): self
    {
        if (!$this->attributes->contains($itemAttribute)) {
            $this->attributes[] = $itemAttribute;
            $itemAttribute->setItem($this);
        }

        return $this;
    }

    public function removeItemAttribute(ItemAttribute $itemAttribute): self
    {
        if ($this->attributes->removeElement($itemAttribute)) {
            // set the owning side to null (unless already changed)
            if ($itemAttribute->getItemId() === $this) {
                $itemAttribute->setItemId(null);
            }
        }

        return $this;
    }

    public function getCollection(): ?Collection
    {
        return $this->collection;
    }

    public function setCollection(?Collection $collection): self
    {
        $this->collection = $collection;

        return $this;
    }

    /**
     * @return Collection|Like[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function getCountLikes(): string
    {
        $count = 0;
        if ($this->likes) {
            foreach ($this->likes as $like) {
                if($like->getIsActive()) $count++;
            }
        }
        return $count;
    }

    public function checkLike(?User $user): bool
    {
        if ($this->likes) {
            foreach ($this->likes as $like) {
                if($like->checkUser($user)) return true;
            }
        }
        return false;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setItem($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getItem() === $this) {
                $like->setItem(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tags[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tags $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tags $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function clearTags(): self
    {
        $this->tags->clear();

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $Name;

    #[ORM\Column(type: 'boolean')]
    private $isActive;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Like::class)]
    private $likes;

    public function __construct()
    {
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * @return Collection|Like[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getUser() === $this) {
                $like->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/Main/ItemController.php
<?php

namespace App\Controller\Main;

use App\Entity\Comment;
use App\Entity\Item;
use App\Entity\Like;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class ItemController extends AbstractController
{
    #[Route('/item/{id}', name: 'item', requirements: ['id' => '\d+'])]
    public function index(int $id, Request $request, EntityManagerInterface $entityManager): Response
    {
        $comment = new Comment();
        $item = $entityManager->getRepository(Item::class)->findOneBy(['id'=>$id]);
        $comments = $entityManager->getRepository(Comment::class)->findBy(['item'=>$id]);
        $user = $this->getUser();
        $like = $entityManager->getRepository(Like::class)->findOneBy(['user' => $user,'item' => $item]);
        $form = $this->createForm(CommentType::class,$comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $comment->setItem($item);
            $comment->setCreateAt(new \DateTime());
            $comment->setUser($user);
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('item', array('id' => $id));
        }

        $forRender['itemForm'] = $form->createView();
        $forRender['like'] = $like;
        $forRender['item'] = $item;
        $forRender['comments'] = $comments;
        $forRender['id'] = $id;

        return $this->render('main/item/index.html.twig', $forRender);
    }
}

src/Controller/Main/ItemLikeController.php
<?php

namespace App\Controller\Main;

use App\Entity\Item;
use App\Entity\Like;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ItemLikeController extends AbstractController
{
    #[Route('/item/{id}/like', name: 'item_like', requirements: ['id' => '\d+'])]
    public function index(int $id, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        $item = $entityManager->getRepository(Item::class)->findOneBy(['id'=>$id]);
        $like = $entityManager->getRepository(Like::class)->findOneBy(['user' => $user,'item' => $item]);

        if (!$like) {

            $like = new Like();
            $like->setUser($user);
            $like->setItem($item);
            $like->setIsActive(true);
        }
        elseif (!$like->getIsActive()) {
            $like->setIsActive(true);
        }
        else {
            $like->setIsActive(false);
        }

        $entityManager->persist($like);
        $entityManager->flush();

        return $this->redirectToRoute('item', array('id' => $id));
    }
}

src/Controller/Main/ItemsCollectionController.php
<?php

namespace App\Controller\Main;

use App\Entity\Collection;
use App\Entity\Comment;
use App\Entity\Item;
//use phpDocumentor\Reflection\DocBlock\Tags\Method;
use App\Entity\CollectionAttribute;
use App\Entity\ItemAttribute;
use App\Entity\Tags;
use App\Form\ItemType;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\Types\This;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ItemsCollectionController extends AbstractController
{
    #[Route('/collection/{id}', name: 'main_items_collection', requirements: ['id' => '\d+'])]
    public function index(int $id, EntityManagerInterface $entityManager): Response
    {
        $item = $entityManager->getRepository(Item::class)->findBy(['collection' => $id]);
        $collection = $entityManager->getRepository(Collection::class)->findOneBy(['id'=> $id]);

        return $this->render('main/items_collection/index.html.twig',  array(
            'collection' => $collection,
            'items' => $item,
            'title' => 'Items',
            'id' =>$id,
        ));
    }

    #[Route('collection/{id}/item/create', name: 'main_user_item_create', requirements: ['id' => '\d+'])]
    public function createItem(Request $request,
                               EntityManagerInterface $entityManager,
                               int $id
    ): Response
    {
        $collection = $entityManager->getRepository(Collection::class)->find(['id' => $id]);

        if (null === $collection) {
            return $this->redirectToRoute('home');
        }

        $item = new Item();
        $item->setCollection($collection);

        foreach ($collection->getAttributes() as $attribute) {
            $item->addItemAttribute((new ItemAttribute())->setItem($item)->setCollectionAttribute($attribute));
        }

        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $item->setCreateDate(new \DateTime());
            $entityManager->persist($item);
            $entityManager->flush();

            return $this->redirectToRoute('main_items_collection', array('id' => $id));
        }

        $forRender['title'] = 'Item creation';
        $forRender['itemForm'] = $form->createView();

        return $this->render('main/items_collection/form.html.twig', $forRender);
    }

    #[Route('/item/{id}/edit/', name: 'item_edit', requirements: ['id' => '\d+'])]
    public function editItem(Request $request, EntityManagerInterface $entityManager, int $id): Response
    {
        $item = $entityManager->getRepository(Item::class)->find(['id' => $id]);
        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('main_items_collection', array('id' => $id));
        }

        $forRender['title'] = 'Item edit';
        $forRender['itemForm'] = $form->createView();

        return $this->render('main/items_collection/form.html.twig', $forRender);
    }

    #[Route('/item/{id}/delete/', name: 'item_delete', requirements: ['id' => '\d+'])]
    public function deleteItem(Request $request, EntityManagerInterface $entityManager, int $id): Response
    {
        $item = $entityManager->getRepository(Item::class)->findOneBy(['id' => $id]);
        $col_id = $item->getCollection()->getId();
        $comments = $entityManager->getRepository(Comment::class)->findBy(['item' => $id]);

        foreach ($comments as $comment) {
            $entityManager->remove($comment);
        }
        $entityManager->remove($item);
        $entityManager->flush();

        return $this->redirectToRoute('main_items_collection', array('id' => $col_id));
    }

}

src/Controller/Main/RegistrationController.php
<?php

namespace App\Controller\Main;

use App\Entity\User;
use App\Form\RegistrationFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class RegistrationController extends AbstractController
{
    #[Route('/register', name: 'app_register')]
    public function register(Request $request,
                             UserPasswordHasherInterface $userPasswordHasher,
                             EntityManagerInterface $entityManager
    ): Response
    {
        $user = new User();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user->setPassword(
            $userPasswordHasher->hashPassword(
                $user,$form->get('plainPassword')->getData()
            ));
            $user->setIsActive(true);
            $user->setRoles((array)'ROLE_USER');
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('registration/register.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }
}

templates/main/item/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ItemController!{% endblock %}

{% block body %}
<div class="container">
    <div class="example-wrapper w-100">
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            {% if app.user == item.collection.user or 'ROLE_ADMIN' in app.user.roles %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a type="button" class="btn btn-outline-primary mb-2" href="{{ path('item_edit', {'id': item.id}) }}">Edit</a>
                <a type="button" class="btn btn-outline-primary mb-2" href="{{ path('item_delete', {'id': item.id}) }}">Delete</a>
            </div>
            {% endif %}
        {% endif %}
        <div class="row row-cols-1 row-cols-md-1 mb-3">
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal  text-center">{{ item.title }}</h4>
                        <div class="row">
                            <div class="col-12">
                                Created at : {{ item.createDate|date('m-d-y') }}
                            </div>
                        </div>
                        {% for attribute in item.attributes %}
                            <div class="row">
                                <div class="col-12">
                                    <label>{{ attribute.collectionAttribute.name ~ ' : ' ~ attribute.value  }}</label>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                {% if app.user %}
                    {% if item.checkLike(app.user) %}
                        <a type="button" class="btn btn-primary mb-2" href="{{ path('item_like', {'id': id }) }}">Like</a>
                    {% else %}
                        <a type="button" class="btn btn-outline-primary mb-2" href="{{ path('item_like', {'id': id }) }}">Like</a>
                    {% endif %}
                    {{ item.countLikes }}
                {% else %}
                    Like:{{ item.countLikes }}
                {% endif %}

                <div class="d-flex justify-content-center row">
                    <div class="d-flex flex-column comment-section">
                        <h6>Comments</h6>
                        {% if (comments != null) %}
                            {% for comment in comments %}
                                <div class="row">
                                    <div class="col">
                                        <div class="card mb-2 shadow-sm">
                                            <div class="card-header py-2">
                                                <h class="my-0 fw-normal"> {{ comment.user.name }}</h>
                                                <h>{{ comment.createAt|date('d-m-Y H:i:s') }}</h>
                                            </div>
                                            <div class="card-body">
                                                {{ comment.content }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                            <div class="mt-4">
                                {{ form_start(itemForm) }}
                                <label class="w-100">
                                    {{ form_widget(itemForm.content, { 'attr': {'class': 'form-control ml-1 shadow-none textarea'} }) }}
                                </label>
                                <div class="mt-2 text-right">
                                    {{ form_widget(itemForm.post, { 'attr': {'class':"btn btn-primary btn-sm shadow-none"}}) }}
                                </div>
                                {{ form_end(itemForm) }}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}