src/Entity/Collections.php
<?php

namespace App\Entity;

use App\Repository\CollectionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CollectionsRepository::class)]
class Collections
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'string', length: 500, nullable: true)]
    private $image;

    #[ORM\ManyToOne(targetEntity: User::class)]
    private $User;

    #[ORM\ManyToOne(targetEntity: Theme::class)]
    private $Theme;

    #[ORM\OneToMany(mappedBy: 'collectionId', targetEntity: ItemCollectionAttribute::class, orphanRemoval: true, cascade:['persist'])]
    private $itemCollectionAttributes;

    public function __construct()
    {
        $this->itemCollectionAttributes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getTheme(): ?Theme
    {
        return $this->Theme;
    }

    public function setTheme(?Theme $Theme): self
    {
        $this->Theme = $Theme;

        return $this;
    }

    /**
     * @return Collection|ItemCollectionAttribute[]
     */
    public function getItemCollectionAttributes(): Collection
    {
        return $this->itemCollectionAttributes;
    }

    public function addItemCollectionAttribute(ItemCollectionAttribute $itemCollectionAttribute): self
    {
        if (!$this->itemCollectionAttributes->contains($itemCollectionAttribute)) {
            $this->itemCollectionAttributes[] = $itemCollectionAttribute;
            $itemCollectionAttribute->setCollectionId($this);
        }

        return $this;
    }

    public function removeItemCollectionAttribute(ItemCollectionAttribute $itemCollectionAttribute): self
    {
        if ($this->itemCollectionAttributes->removeElement($itemCollectionAttribute)) {
            // set the owning side to null (unless already changed)
            if ($itemCollectionAttribute->getCollectionId() === $this) {
                $itemCollectionAttribute->setCollectionId(null);
            }
        }

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $Name;

    #[ORM\Column(type: 'boolean')]
    private $isActive;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Like::class)]
    private $likes;

    public function __construct()
    {
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * @return Collection|Like[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getUser() === $this) {
                $like->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/Main/ItemController.php
<?php

namespace App\Controller\Main;

use App\Entity\Comment;
use App\Entity\Item;
use App\Entity\Like;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class ItemController extends AbstractController
{
    #[Route('/item/{id}', name: 'item', requirements: ['id' => '\d+'])]
    public function index(int $id, Request $request, EntityManagerInterface $entityManager): Response
    {
        $comment = new Comment();
        $item = $entityManager->getRepository(Item::class)->findOneBy(['id'=>$id]);
        $comments = $entityManager->getRepository(Comment::class)->findBy(['item'=>$id]);
        $user = $this->getUser();
        $like = $entityManager->getRepository(Like::class)->findOneBy(['user' => $user,'item' => $item]);
        $form = $this->createForm(CommentType::class,$comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $comment->setItem($item);
            $comment->setCreateAt(new \DateTime());
            $comment->setUser($user);
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('item', array('id' => $id));
        }

        $forRender['itemForm'] = $form->createView();
        $forRender['like'] = $like;
        $forRender['item'] = $item;
        $forRender['comments'] = $comments;
        $forRender['id'] = $id;

        return $this->render('main/item/index.html.twig', $forRender);
    }
}

src/Controller/Main/ItemLikeController.php
<?php

namespace App\Controller\Main;

use App\Entity\Item;
use App\Entity\Like;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ItemLikeController extends AbstractController
{
    #[Route('/item/{id}/like', name: 'item_like', requirements: ['id' => '\d+'])]
    public function index(int $id, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        $item = $entityManager->getRepository(Item::class)->findOneBy(['id'=>$id]);
        $like = $entityManager->getRepository(Like::class)->findOneBy(['user' => $user,'item' => $item]);

        if (!$like) {

            $like = new Like();
            $like->setUser($user);
            $like->setItem($item);
            $like->setIsActive(true);
        }
        elseif (!$like->getIsActive()) {
            $like->setIsActive(true);
        }
        else {
            $like->setIsActive(false);
        }

        $entityManager->persist($like);
        $entityManager->flush();

        return $this->redirectToRoute('item', array('id' => $id));
    }
}

src/Controller/Main/ItemsCollectionController.php
<?php

namespace App\Controller\Main;

use App\Entity\Collection;
use App\Entity\Comment;
use App\Entity\Item;
//use phpDocumentor\Reflection\DocBlock\Tags\Method;
use App\Entity\CollectionAttribute;
use App\Entity\ItemAttribute;
use App\Entity\Tags;
use App\Form\ItemType;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\Types\This;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ItemsCollectionController extends AbstractController
{
    #[Route('/collection/{id}', name: 'main_items_collection', requirements: ['id' => '\d+'])]
    public function index(int $id, EntityManagerInterface $entityManager): Response
    {
        $item = $entityManager->getRepository(Item::class)->findBy(['collection' => $id]);
        $collection = $entityManager->getRepository(Collection::class)->findOneBy(['id'=> $id]);

        return $this->render('main/items_collection/index.html.twig',  array(
            'collection' => $collection,
            'items' => $item,
            'title' => 'Items',
            'id' =>$id,
        ));
    }

    #[Route('collection/{id}/item/create', name: 'main_user_item_create', requirements: ['id' => '\d+'])]
    public function createItem(Request $request,
                               EntityManagerInterface $entityManager,
                               int $id
    ): Response
    {
        $collection = $entityManager->getRepository(Collection::class)->find(['id' => $id]);

        if (null === $collection) {
            return $this->redirectToRoute('home');
        }

        $item = new Item();
        $item->setCollection($collection);

        foreach ($collection->getAttributes() as $attribute) {
            $item->addItemAttribute((new ItemAttribute())->setItem($item)->setCollectionAttribute($attribute));
        }

        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $item->setCreateDate(new \DateTime());
            $entityManager->persist($item);
            $entityManager->flush();

            return $this->redirectToRoute('main_items_collection', array('id' => $id));
        }

        $forRender['title'] = 'Item creation';
        $forRender['itemForm'] = $form->createView();

        return $this->render('main/items_collection/form.html.twig', $forRender);
    }

    #[Route('/item/{id}/edit/', name: 'item_edit', requirements: ['id' => '\d+'])]
    public function editItem(Request $request, EntityManagerInterface $entityManager, int $id): Response
    {
        $item = $entityManager->getRepository(Item::class)->find(['id' => $id]);
        $form = $this->createForm(ItemType::class, $item);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('main_items_collection', array('id' => $id));
        }

        $forRender['title'] = 'Item edit';
        $forRender['itemForm'] = $form->createView();

        return $this->render('main/items_collection/form.html.twig', $forRender);
    }

    #[Route('/item/{id}/delete/', name: 'item_delete', requirements: ['id' => '\d+'])]
    public function deleteItem(Request $request, EntityManagerInterface $entityManager, int $id): Response
    {
        $item = $entityManager->getRepository(Item::class)->findOneBy(['id' => $id]);
        $col_id = $item->getCollection()->getId();
        $comments = $entityManager->getRepository(Comment::class)->findBy(['item' => $id]);

        foreach ($comments as $comment) {
            $entityManager->remove($comment);
        }
        $entityManager->remove($item);
        $entityManager->flush();

        return $this->redirectToRoute('main_items_collection', array('id' => $col_id));
    }

}

src/Controller/Main/RegistrationController.php
<?php

namespace App\Controller\Main;

use App\Entity\User;
use App\Form\RegistrationFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class RegistrationController extends AbstractController
{
    #[Route('/register', name: 'app_register')]
    public function register(Request $request,
                             UserPasswordHasherInterface $userPasswordHasher,
                             EntityManagerInterface $entityManager
    ): Response
    {
        $user = new User();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user->setPassword(
            $userPasswordHasher->hashPassword(
                $user,$form->get('plainPassword')->getData()
            ));
            $user->setIsActive(true);
            $user->setRoles((array)'ROLE_USER');
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('registration/register.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }
}

src/Controller/Main/TagsController.php
<?php

namespace App\Controller\Main;

use App\Entity\Tags;
use App\Form\TagsType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TagsController extends AbstractController
{
    #[Route('/tags', name: 'tags')]
    public function index(): Response
    {
        $tags = $this->getDoctrine()->getRepository(Tags::class)->findAll();

        return $this->render('main/tags/index.html.twig', array(
            'tags' => $tags,
            'title' => 'Tags',
        ));
    }

    #[Route('/tags/add', name: 'add_tags')]
    public function addTag(Request $request, EntityManagerInterface $entityManager): Response
    {
        $tag = new Tags();
        $form = $this->createForm(TagsType::class, $tag);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($tag);
            $entityManager->flush();

            return $this->redirectToRoute('main_tags');
        }
        $forRender['title'] = 'tag creation';
        $forRender['addtagForm'] = $form->createView();
        return $this->render('main/tags/form.html.twig', $forRender);
    }


}

templates/main/my_collections/form.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    {{ form_start(collectionForm) }}

    <div class="form-login">
        <div class="col-12">
            <h1 class="h3 mb-3 font-weight-normal">{{ title }}</h1>
            <div class="col-sm-12">
                {{ form_label(collectionForm.title) }}
                {{ form_widget(collectionForm.title, {'attr': {'class': 'form-control','placeholder ':'Enter Collections title'} }) }}
            </div>
            <div class="col-sm-12">
                {{ form_label(collectionForm.theme) }}
                {{ form_widget(collectionForm.theme, { 'attr': {'class':'form-select'}}) }}
            </div>
            <div class="col-sm-12">
                {{ form_label(collectionForm.image) }}
                {{ form_widget(collectionForm.image, { 'attr': {'class':'form-control'}}) }}
            </div>
            <div class="col-sm-12">
                {{ form_label(collectionForm.description) }}
            </div>
            <div class="col-sm-12">
                {{ form_widget(collectionForm.description, { 'attr': {'class':'form-control'}}) }}
            </div>
            <div class="col-sm-12">
                <ul class="tags"
                    data-index="{{ collectionForm.attributes|length > 0 ? collectionForm.attributes|last.vars.name + 1 : 0 }}"
                    data-prototype="{{ form_widget(collectionForm.attributes.vars.prototype)|e('html_attr') }}"
                ></ul>
                {{ form_widget(collectionForm.attributes) }}
            <button type="button" class="add_item_link btn btn-outline-primary mt-2" data-collection-holder-class="tags">Add attribute to item</button>
            </div>
            <div class="col-sm-12">
                {{ form_widget(collectionForm.save, { 'attr': {'class':'btn btn-outline-primary mt-2'} }) }}
            </div>
        </div>
    </div>
    {{ form_end(collectionForm) }}
    <script>
        const addFormToCollection = (e) => {
            const collectionHolder = document.querySelector('.' + e.currentTarget.dataset.collectionHolderClass);

            const item = document.createElement('li');

            item.innerHTML = collectionHolder
                .dataset
                .prototype
                .replace(
                    /__name__/g,
                    collectionHolder.dataset.index
                );

            collectionHolder.appendChild(item);

            collectionHolder.dataset.index++;
        };
        document
            .querySelectorAll('.add_item_link')
            .forEach(btn => {
                btn.addEventListener("click", addFormToCollection)
            });

    </script>
{% endblock %}

templates/main/my_collections/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{title}}{% endblock %}

{% block body %}

    <div class="container">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a type="button" class="btn btn-outline-primary mb-2" href="{{ path('main_user_collections_create') }}">Add Collection</a>
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            {% for collection in collections %}
                <div class="col">
                    <div class="card mb-4 rounded-3 shadow-sm">
                        <div class="card-header py-3">
                            <h4 class="my-0 fw-normal">{{ collection.title }}</h4>
                        </div>
                        <div class="card-body">
                            {% if collection.image %}
                                <div class="col-4 text-center" style="width: 300px;">
                                        <img src="{{ collection.image }}" class="img-fluid" style="max-height: 200px; max-width: 300px;">
                                </div>
                            {% endif %}
                            <ul class="list-unstyled mt-3 mb-4">
                                <li>{{ collection.description }}</li>
                            </ul>
                            <a type="button" class="w-100 btn btn-lg btn-outline-primary" href="{{ path('main_items_collection', {'id': collection.id}) }}">Look</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}